services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=household
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    platform: linux/amd64
volumes:
  db-volume: